In [1]:
import numpy as np
import pandas as pd

What's the version of NumPy that you installed?

In [2]:
np.__version__

'1.18.1'

What's the version of Pandas?

In [3]:
pd.__version__

'1.0.1'

In [4]:
data = pd.read_csv("C:/Users/Shreetama/Desktop/data science learning/data zoomcamp/cars_data.csv")

In [5]:
data.head()

Make       Model  Year             Engine Fuel Type  Engine HP  \
0  BMW  1 Series M  2011  premium unleaded (required)      335.0   
1  BMW    1 Series  2011  premium unleaded (required)      300.0   
2  BMW    1 Series  2011  premium unleaded (required)      300.0   
3  BMW    1 Series  2011  premium unleaded (required)      230.0   
4  BMW    1 Series  2011  premium unleaded (required)      230.0   

   Engine Cylinders Transmission Type     Driven_Wheels  Number of Doors  \
0               6.0            MANUAL  rear wheel drive              2.0   
1               6.0            MANUAL  rear wheel drive              2.0   
2               6.0            MANUAL  rear wheel drive              2.0   
3               6.0            MANUAL  rear wheel drive              2.0   
4               6.0            MANUAL  rear wheel drive              2.0   

                         Market Category Vehicle Size Vehicle Style  \
0  Factory Tuner,Luxury,High-Performance      Compact         Coupe   
1                     Luxury,Performance      Compact   Convertible   
2                Luxury,High-Performance      Compact         Coupe   
3                     Luxury,Performance      Compact         Coupe   
4                                 Luxury      Compact   Convertible   

   highway MPG  city mpg  Popularity   MSRP  
0           26        19        3916  46135  
1           28        19        3916  40650  
2           28        20        3916  36350  
3           28        18        3916  29450  
4           28        18        3916  34500

In [6]:
bmw = data[(data["Make"] == "BMW")]


In [7]:
pd.pivot_table(data, values = "MSRP", index = "Make", aggfunc = np.mean)

MSRP
Make                       
Acura          3.488759e+04
Alfa Romeo     6.160000e+04
Aston Martin   1.979104e+05
Audi           5.345211e+04
BMW            6.154676e+04
Bentley        2.471693e+05
Bugatti        1.757224e+06
Buick          2.820661e+04
Cadillac       5.623132e+04
Chevrolet      2.835039e+04
Chrysler       2.672296e+04
Dodge          2.239006e+04
FIAT           2.267024e+04
Ferrari        2.382188e+05
Ford           2.739927e+04
GMC            3.049330e+04
Genesis        4.661667e+04
HUMMER         3.646441e+04
Honda          2.667434e+04
Hyundai        2.459704e+04
Infiniti       4.239421e+04
Kia            2.531017e+04
Lamborghini    3.315673e+05
Land Rover     6.782322e+04
Lexus          4.754907e+04
Lincoln        4.283983e+04
Lotus          6.918828e+04
Maserati       1.142077e+05
Maybach        5.462219e+05
Mazda          2.003938e+04
McLaren        2.398050e+05
Mercedes-Benz  7.147623e+04
Mitsubishi     2.124054e+04
Nissan         2.858343e+04
Oldsmobile     1.154254e+04
Plymouth       3.122902e+03
Pontiac        1.932155e+04
Porsche        1.016224e+05
Rolls-Royce    3.511306e+05
Saab           2.741350e+04
Scion          1.993250e+04
Spyker         2.133233e+05
Subaru         2.482750e+04
Suzuki         1.790721e+04
Tesla          8.525556e+04
Toyota         2.903002e+04
Volkswagen     2.810238e+04
Volvo          2.854116e+04

What's the average price of BMW cars in the dataset?

In [8]:
pd.pivot_table(bmw, values = "MSRP", index = "Make", aggfunc = np.mean)

MSRP
Make              
BMW   61546.763473

What's the average price of BMW cars in the dataset?

In [9]:
pd.pivot_table(data[(data["Make"] == "BMW")], values = "MSRP", index = "Make", aggfunc = np.mean)

MSRP
Make              
BMW   61546.763473

In [85]:
cars_2015 = data[(data["Year"] >= 2015)]
np.sum(cars_2015.isna())

Make                    0
Model                   0
Year                    0
Engine Fuel Type        0
Engine HP              51
Engine Cylinders        8
Transmission Type       0
Driven_Wheels           0
Number of Doors         5
Market Category      1324
Vehicle Size            0
Vehicle Style           0
highway MPG             0
city mpg                0
Popularity              0
MSRP                    0
Engine HP_after         0
dtype: int64

In [86]:
mean_hp_before = np.mean(data["Engine HP"])

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP?

Select a subset of cars after year 2015 (inclusive, i.e. 2015 and after). How many of them have missing values for Engine HP

In [88]:
np.sum(data["Engine HP"].isna())

69

Calculate the average "Engine HP" in the dataset.
Use the fillna method and to fill the missing values in "Engine HP" with the mean value from the previous step.
Now, calcualte the average of "Engine HP" again.
Has it changed?

In [89]:
data["Engine HP_after"] = data["Engine HP"].fillna(mean_hp_before)

In [90]:
mean_hp_after = np.mean(data["Engine HP_after"])

print(round(mean_hp_before))
print(round(mean_hp_after))


249
249


In [63]:
rolls_roy = data[(data["Make"] == "Rolls-Royce")]
rr = rolls_roy[["Engine HP", "Engine Cylinders", "highway MPG"]]
rr_dd = rr.drop_duplicates()
rr_dd.head(8)

Engine HP  Engine Cylinders  highway MPG
2921       325.0               8.0           15
3505       563.0              12.0           19
5275       563.0              12.0           21
5279       563.0              12.0           20
7443       322.0              12.0           15
7553       453.0              12.0           19
11448      624.0              12.0           21

Select all the "Rolls-Royce" cars from the dataset.
Select only columns "Engine HP", "Engine Cylinders", "highway MPG".
Now drop all duplicated rows using drop_duplicates method (you should get a dataframe with 7 rows).
Get the underlying NumPy array. Let's call it X.
Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.
Invert XTX.
What's the sum of all the elements of the result?
Hint: if the result is negative, re-read the task one more time

In [64]:
X = rr_dd.to_numpy()

In [65]:
X_T = X.transpose()
print(X_T)

[[325. 563. 563. 563. 322. 453. 624.]
 [  8.  12.  12.  12.  12.  12.  12.]
 [ 15.  19.  21.  20.  15.  19.  21.]]


In [91]:
XTX = np.matmul(X_T, X)
print(XTX)

[[1.754801e+06 3.965600e+04 6.519600e+04]
 [3.965600e+04 9.280000e+02 1.500000e+03]
 [6.519600e+04 1.500000e+03 2.454000e+03]]


In [92]:
XTX_inv = np.linalg.inv(XTX)
print(XTX_inv)

[[ 5.17815728e-05  9.06587044e-04 -1.92984188e-03]
 [ 9.06587044e-04  1.05723058e-01 -8.87084092e-02]
 [-1.92984188e-03 -8.87084092e-02  1.05900809e-01]]


In [93]:
np.sum(XTX_inv)

0.032212320677486195

Create an array y with values [1000, 1100, 900, 1200, 1000, 850, 1300].
Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.
What's the value of the first element of w?.

In [94]:
y = [1000, 1100, 900, 1200, 1000, 850, 1300]

In [96]:
z = np.matmul(XTX_inv, X_T)

In [98]:
w = np.matmul(z, y)

In [99]:
w[0]

0.19989598183186175